spring:
  application:
    name: "spring-labs"
error-trace:
  stacktrace: true
my:
  name: jinho_test
  age: 30

---
spring:
  config:
    activate:
      on-profile: dev
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true     # 쿼리 로그 포맷 (정렬)
        show_sql: true       # 쿼리 로그 출력
  datasource:
    url: jdbc:mysql://localhost:13306/fastcamp_labs?serverTimezone=UTC&characterEncoding=UTF-8
    username: fastcamp
    password: testlabs
    driver-class-name: com.mysql.cj.jdbc.Driver


my:
  name: jinho_dev
  age: 34

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: none # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true     # 쿼리 로그 포맷 (정렬)
        show_sql: true       # 쿼리 로그 출력
  datasource:
    url: jdbc:mysql://localhost:13306/fastcamp_labs?serverTimezone=UTC&characterEncoding=UTF-8
    username: fastcamp
    password: testlabs
    driver-class-name: com.mysql.cj.jdbc.Driver

