services:
  mysql:
    image: mysql:8.0.33
    ports:
      - 13306:3306
    volumes:
      - /Users/jinho/IdeaProjects/spring-labs/src/main/resources/initdb:/docker-entrypoint-initdb.d
#      - /Users/black/IdeaProjects/jedi-spring-labs/src/main/resources/initdb:/docker-entrypoint-initdb.d
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: testbed
      MYSQL_DATABASE: service-labs
