openapi: 3.0.1
info:
  title: FastEcommerce - Order/Payment
  description: Order/Payment API
  version: 0.1.0
servers:
- url: https://localhost:8080
tags: []
paths:
  /order/new:
    post:
      tags:
      - order
      operationId: new-order
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/order-new-972061452'
            examples:
              new-order:
                value: "{\"orderer\":{\"name\":\"유진호\",\"phoneNumber\":\"010-1234-1234\"\
                  },\"newlyOrderedItem\":[{\"itemIdx\":1,\"productId\":\"eb2a5f23-f851-4b58-9ea1-a36d606b1f75\"\
                  ,\"productName\":\"농심 짜파게티 4봉\",\"price\":4500,\"quantity\":1,\"\
                  amounts\":4500}]}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order-new486549215'
              examples:
                new-order:
                  value: "{\"status\":\"SUCCESS\",\"body\":{\"orderId\":\"43696578-df4b-49b6-a526-6ba3b5b4df3f\"\
                    ,\"orderer\":{\"name\":\"유진호\",\"phoneNumber\":\"010-1234-1234\"\
                    },\"paymentId\":\"c538f7b9-f310-43ea-9e6e-f832e947a889\",\"totalPrice\"\
                    :0,\"status\":\"ORDER_COMPLETED\",\"items\":[{\"itemIdx\":1,\"\
                    productId\":\"eb2a5f23-f851-4b58-9ea1-a36d606b1f75\",\"productName\"\
                    :\"농심 짜파게티 4봉\",\"price\":4500,\"size\":\"FREE\",\"amount\":0,\"\
                    quantity\":0,\"state\":\"ORDER_COMPLETED\"}]},\"timestamp\":\"\
                    2024-06-21T11:23:25.975175\"}"
components:
  schemas:
    order-new-972061452:
      type: object
      properties:
        newlyOrderedItem:
          type: array
          items:
            type: object
            properties:
              quantity:
                type: number
                description: ""
              amounts:
                type: number
                description: ""
              productId:
                type: string
                description: ""
              price:
                type: number
                description: ""
              itemIdx:
                type: number
                description: ""
              productName:
                type: string
                description: ""
        orderer:
          type: object
          properties:
            phoneNumber:
              type: string
              description: 주문자 휴대전화 번호
            name:
              type: string
              description: 주문자명
    order-new486549215:
      type: object
